import io
import os
import re
import zipfile
from typing import List, Tuple

import soundfile as sf
import streamlit as st
from pydub import AudioSegment
from pydub.silence import detect_leading_silence

# Heavy imports guarded to app runtime
from kokoro import KPipeline


def trim_tail_silence(audio_segment: AudioSegment, silence_threshold: float = -50.0, chunk_size: int = 10) -> AudioSegment:
    reversed_sound = audio_segment.reverse()
    silence_duration = detect_leading_silence(
        reversed_sound,
        silence_threshold=silence_threshold,
        chunk_size=chunk_size,
    )
    return reversed_sound[silence_duration:].reverse()


LANGUAGE_LABELS = {
    "a": "American English",
    "b": "British English",
    "j": "Japanese",
    "e": "Spanish",
    "f": "French",
    "h": "Hindi",
    "i": "Italian",
    "p": "Portuguese",
    "z": "Chinese",
}


def _sanitize_filename(name: str) -> str:
    base = re.sub(r"[^A-Za-z0-9._-]", "_", name.strip())
    if not base.lower().endswith(".wav"):
        base += ".wav"
    return base


@st.cache_resource(show_spinner=False)
def get_pipeline(lang_code: str) -> KPipeline:
    # 1) Normal init
    try:
        return KPipeline(lang_code=lang_code)
    except Exception as first_err:
        # 2) If Japanese, try unidic-lite (no network, bundled dict)
        if lang_code == "j":
            try:
                import unidic_lite  # type: ignore

                # Ensure unidic-lite is installed and discoverable
                if hasattr(unidic_lite, "install"):
                    unidic_lite.install()
                # Hint fugashi to use unidic-lite dictionary
                if hasattr(unidic_lite, "DICDIR"):
                    os.environ["FUGASHI_DIC_DIR"] = getattr(unidic_lite, "DICDIR")
                return KPipeline(lang_code=lang_code)
            except Exception:
                # 3) Fallback to full unidic download if lite is unavailable
                try:
                    import unidic  # type: ignore

                    unidic.download()
                    # Point fugashi to the installed unidic
                    if hasattr(unidic, "DICDIR"):
                        dicdir = getattr(unidic, "DICDIR")
                        os.environ["FUGASHI_DIC_DIR"] = dicdir
                        mecabrc = os.path.join(dicdir, "mecabrc")
                        if os.path.exists(mecabrc):
                            os.environ["MECABRC"] = mecabrc
                    return KPipeline(lang_code=lang_code)
                except Exception:
                    raise first_err
        # Non-Japanese or unrecoverable
        raise first_err


def parse_rows(text_area_value: str) -> List[Tuple[str, str]]:
    rows: List[Tuple[str, str]] = []
    for raw in text_area_value.splitlines():
        line = raw.strip()
        if not line:
            continue
        if "," in line:
            t, fn = line.split(",", 1)
            rows.append((t.strip(), _sanitize_filename(fn.strip())))
        else:
            # If only one token, use it as text and autogenerated filename idx
            rows.append((line, None))
    # Backfill filenames for any None entries
    auto_i = 1
    finalized: List[Tuple[str, str]] = []
    for t, fn in rows:
        if fn is None:
            fn = _sanitize_filename(f"audio_{auto_i:03d}")
            auto_i += 1
        finalized.append((t, fn))
    return finalized


def synthesize_to_wav_bytes(pipeline: KPipeline, text: str, voice: str, speed: float) -> bytes:
    generator = pipeline(text, voice=voice, speed=speed, split_pattern=r"\n+")
    for _i, (_gs, _ps, audio) in enumerate(generator):
        buf = io.BytesIO()
        sf.write(buf, audio, 24000, format="WAV")
        return buf.getvalue()
    raise RuntimeError("No audio returned by pipeline")


def trim_wav_bytes(wav_bytes: bytes, silence_threshold: float, chunk_size: int) -> bytes:
    src = io.BytesIO(wav_bytes)
    seg = AudioSegment.from_file(src, format="wav")
    trimmed = trim_tail_silence(seg, silence_threshold=silence_threshold, chunk_size=chunk_size)
    out = io.BytesIO()
    trimmed.export(out, format="wav")
    return out.getvalue()


st.set_page_config(page_title="Kokoro TTS Bulk Generator", page_icon="🔊", layout="wide")

st.title("🔊 Kokoro TTS Bulk Generator")

with st.sidebar:
    st.header("Settings")
    lang_code = st.selectbox(
        "Language",
        options=list(LANGUAGE_LABELS.keys()),
        format_func=lambda c: f"{LANGUAGE_LABELS.get(c, c)} ({c})",
        index=list(LANGUAGE_LABELS.keys()).index("j") if "j" in LANGUAGE_LABELS else 0,
    )
    voice = st.text_input(
        "Voice ID",
        value="af_heart",
        help="Enter a valid Kokoro voice ID (e.g., af_heart).",
    )
    speed = st.slider("Speed", min_value=0.5, max_value=1.5, value=1.0, step=0.05)

    st.divider()
    st.subheader("Silence Removal")
    do_trim = st.checkbox("Trim trailing silence before zip", value=True)
    silence_threshold = st.slider("Silence threshold (dBFS)", -80, -10, -50, 1)
    chunk_size = st.slider("Chunk size (ms)", 2, 50, 10, 1)

st.markdown(
    """
Provide your lines below as:
- text,filename  (comma separated)
- One entry per line
- .wav extension is optional and will be added automatically

Example:
```
January, month_01
Yesterday was, phrase_yesterday
```
    """
)

input_mode = st.radio("Input mode", ["Paste list", "Upload CSV"], horizontal=True)
rows: List[Tuple[str, str]] = []

if input_mode == "Paste list":
    data_text = st.text_area("Lines", height=220)
    if st.button("Parse", type="secondary") or data_text:
        try:
            rows = parse_rows(data_text)
            st.success(f"Parsed {len(rows)} rows")
        except Exception as e:
            st.error(f"Parse error: {e}")
else:
    file = st.file_uploader("Upload a CSV with columns: text,filename", type=["csv"]) 
    if file is not None:
        try:
            content = file.read().decode("utf-8")
            rows = parse_rows(content)
            st.success(f"Loaded {len(rows)} rows from CSV")
        except Exception as e:
            st.error(f"Failed to read CSV: {e}")

if rows:
    st.dataframe({"text": [t for t, _ in rows], "filename": [f for _, f in rows]}, use_container_width=True, hide_index=True)

col1, col2 = st.columns([1, 2])
with col1:
    gen_btn = st.button(
        f"Generate {len(rows)} files" if rows else "Generate",
        type="primary",
        use_container_width=True,
        disabled=not rows,
    )
with col2:
    zip_placeholder = st.empty()

if gen_btn and rows:
    try:
        pipe = get_pipeline(lang_code)
    except Exception as e:
        st.error(f"Failed to initialize pipeline: {e}")
        st.stop()

    progress = st.progress(0.0)
    status = st.empty()

    zip_mem = io.BytesIO()
    errors: List[str] = []

    with zipfile.ZipFile(zip_mem, "w", compression=zipfile.ZIP_DEFLATED) as zipf:
        for i, (text, fname) in enumerate(rows):
            status.info(f"Processing {i+1}/{len(rows)}: {fname}")
            try:
                wav_bytes = synthesize_to_wav_bytes(pipe, text, voice, speed)
                if do_trim:
                    wav_bytes = trim_wav_bytes(wav_bytes, silence_threshold, chunk_size)
                zipf.writestr(fname, wav_bytes)
            except Exception as e:
                errors.append(f"{fname}: {e}")
            progress.progress((i + 1) / max(1, len(rows)))

    zip_mem.seek(0)

    if errors:
        st.warning("Some files failed:")
        st.code("\n".join(errors))

    zip_bytes = zip_mem.getvalue()
    st.success(f"Done! {len(rows) - len(errors)} succeeded, {len(errors)} failed.")
    zip_placeholder.download_button(
        label="⬇️ Download ZIP",
        data=zip_bytes,
        file_name="kokoro_tts_batch.zip",
        mime="application/zip",
        use_container_width=True,
    )
